%Andrew Bauer
%090313

clear all

%% PROBLEM

%The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

% 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

% Let us list the factors of the first seven triangle numbers:

%  1: 1
%  3: 1,3
%  6: 1,2,3,6
% 10: 1,2,5,10
% 15: 1,3,5,15
% 21: 1,3,7,21
% 28: 1,2,4,7,14,28
% We can see that 28 is the first triangle number to have over five divisors.

%->What is the value of the first triangle number to have over five hundred divisors?

%% GO 

tic

triNo = sum(1:1);
triNoExtent = 2;
flag = 1;

while flag
    triNo = triNo + triNoExtent;
    
    counted = countDivisors_helper_problem12(triNo);
    
%     if mod(triNo,2)       
%         if counted > 5            
%             flag = 0;
%         else
%             triNoExtent = triNoExtent + 1;
%         end
%     else
        if counted > 500
            flag = 0;
            
        else
            triNoExtent = triNoExtent + 1;            
        end
%     end
end

toc

disp(strcat(mfilename,': done'));

%% NOTES

%Elapsed time is 31.277544 seconds on CCBI PC. This code is crap, I know, I
%was debugging so I removed my optimizer sections, can't be arsed to
%re-implement them, so... moving on